language: node_js
node_js: 7

install:
  - bundle install
  - npm install

script: node_modules/.bin/grunt build

before_deploy: node_modules/.bin/grunt build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/sPMgWOuF6PJH3wOC_WX1pzSJusdd5mscismEi1DOrvs"
